CSC237_TripLog_start1/Models/Trip.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CSC237_TripLog_start1.Models
{
    public class Trip
    {
        // EF Core will configure the database to generate this value
        // See page 136 in Murach textbook
        public int TripId { get; set; } //Primary key

        [Required(ErrorMessage = "Please enter a destination.")]
        public string Destination { get; set; }

        [Required(ErrorMessage = "Please enter the date your trip starts.")]
        public DateTime? StartDate { get; set; }

        [Required(ErrorMessage = "Please enter the date your trip ends.")]
        public DateTime? EndDate { get; set; }

        //Accommodation is optional
        public string Accommodation { get; set; }
        public string AccommodationPhone { get; set; }
        public string AccommodationEmail { get; set; }

        // Things to do are optional
        public string ThingToDo1 { get; set; }
        public string ThingToDo2 { get; set; }
        public string ThingToDo3 { get; set; }
    }
}

CSC237_TripLog_start1/Models/TripLogContext.cs
using Microsoft.EntityFrameworkCore;

namespace CSC237_TripLog_start1.Models
{
    public class TripLogContext : DbContext
    {
        public TripLogContext(DbContextOptions<TripLogContext> options)
            : base(options)
        { }

        public DbSet<Trip> Trips { get; set; }
    }
}

CSC237_TripLog_start1/Models/TripViewModel.cs
namespace CSC237_TripLog_start1.Models
{
    public class TripViewModel
    {
        public Trip Trip { get; set; }
        public int PageNumber { get; set; }
    }
}

CSC237_TripLog_start1/Controllers/HomeController.cs
using CSC237_TripLog_start1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CSC237_TripLog_start1.Controllers
{
    public class HomeController : Controller
    {
        private TripLogContext context { get; set; }
        public HomeController(TripLogContext ctx) => context = ctx;

        public ViewResult Index()
        {
            // Change the OrderBy to StartDate
            var trips = context.Trips.OrderBy(t => t.Destination).ToList();
            return View(trips);
        }

    }
}

CSC237_TripLog_start1/Controllers/TripController.cs
using CSC237_TripLog_start1.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CSC237_TripLog_start1.Controllers
{
    public class TripController : Controller
    {
        private TripLogContext context { get; set; }
        public TripController(TripLogContext ctx) => context = ctx;

        public RedirectToActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        /*
         * Defines the Action method called Add
         *    with a return type object of ViewResult
         * Note TripController.Add is the fully qualified method name 
         * Add method defines an optional parameter called id and sets the value to empty string
         *    if the user does not provide a value (See page 168 Murach C# 7th ed. book)
         * Later, id may be set to a page number (as a string)
        */
        public ViewResult Add(string id = "")
        {
            // Create a new instance of the view model
            var vm = new TripViewModel();

            /********************************************************************************************
            * need to pass Accommodation value, or Destination value (depending on page number and 
            * Accommodation value), to by view. 
            * 
            * Accommodation is an optional value - don't need it to persist after being read if it's null.
            * So, do straight read, and if it's not null, use Keep() method to make sure it persists.
            * 
            * Destination is a a required value - always need it to persist after being read. 
            * So, use Peek() method to read it and make sure it persists 
            * Peek() and Keep() see Ch 8 page 309 Murach textbook
            *********************************************************************************************/

            if (id.ToLower() == "page2")
            {
                // New string variable called accommodation can be of nullable type 
                // TempData is a dictionary of key/value pairs where the key is in brackets []
                // The key is a string and the value is an object
                // This code retreives the TempData key (name of the Accommodation)
                //    which can be nullable (the ?)
                var accommodation = TempData[nameof(Trip.Accommodation)]?.ToString();

                if (string.IsNullOrEmpty(accommodation))
                {  // skip to page 3
                    vm.PageNumber = 3;
                    // Notice Destination is not nullable (no question mark)
                    var destination = TempData.Peek(nameof(Trip.Destination)).ToString();
                    vm.Trip = new Trip { Destination = destination };
                    return View("Add3", vm);  //pass the view model to page 3
                }
                else
                {   // Invoked from Page 1, return the Page 2 view to the user
                    //    to capture data about the Accommodation
                    vm.PageNumber = 2;
                    vm.Trip = new Trip { Accommodation = accommodation };
                    TempData.Keep(nameof(Trip.Accommodation));
                    return View("Add2", vm);
                }
            }
            else if (id.ToLower() == "page3")
            {
                vm.PageNumber = 3;
                vm.Trip = new Trip { Destination = TempData.Peek(nameof(Trip.Destination)).ToString() };

                return View("Add3", vm);
            }
            else
            {
                vm.PageNumber = 1;
                return View("Add1", vm);
            }
        }

        [HttpPost]
        public IActionResult Add(TripViewModel vm)
        {
            if (vm.PageNumber == 1)
            {
                if (ModelState.IsValid) // only page 1 has required data
                {
                    /***************************************************
                    * Store data in TempData and redirect (PRG pattern)
                    ****************************************************/
                    TempData[nameof(Trip.Destination)] = vm.Trip.Destination;
                    TempData[nameof(Trip.Accommodation)] = vm.Trip.Accommodation;
                    TempData[nameof(Trip.StartDate)] = vm.Trip.StartDate;
                    TempData[nameof(Trip.EndDate)] = vm.Trip.EndDate;
                    return RedirectToAction("Add", new { id = "Page2" });
                }
                else
                {
                    return View("Add1", vm);
                }
            }
            else if (vm.PageNumber == 2)
            {
                /***************************************************
                    * Store data in TempData and redirect (PRG pattern)
                ****************************************************/
                TempData[nameof(Trip.AccommodationPhone)] = vm.Trip.AccommodationPhone;
                TempData[nameof(Trip.AccommodationEmail)] = vm.Trip.AccommodationEmail;
                return RedirectToAction("Add", new { id = "Page3" });
            }
            else if (vm.PageNumber == 3)
            {
                /***************************************************
                    * Don't need data in TempData to persist after 
                    * updating database, so do straight read.
                ****************************************************/
                vm.Trip.Destination = TempData[nameof(Trip.Destination)].ToString();
                vm.Trip.Accommodation = TempData[nameof(Trip.Accommodation)]?.ToString();
                vm.Trip.StartDate = (DateTime)TempData[nameof(Trip.StartDate)];
                vm.Trip.EndDate = (DateTime)TempData[nameof(Trip.EndDate)];
                vm.Trip.AccommodationPhone = TempData[nameof(Trip.AccommodationPhone)]?.ToString();
                vm.Trip.AccommodationEmail = TempData[nameof(Trip.AccommodationEmail)]?.ToString();

                context.Trips.Add(vm.Trip); //This is a DB Add
                context.SaveChanges();
                TempData["message"] = $"Trip to {vm.Trip.Destination} added.";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public RedirectToActionResult Cancel()
        {
            TempData.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

CSC237_TripLog_start1/Views/Home/Index.cshtml
@model IEnumerable<Trip>

@{
    ViewBag.Title = "My Trip Log";
}

    @*Change the Sort order to StartDate and remove the paragraph from the view*@  
    @*Look in the HomeController for help about how to do this*@ 
    @*Enter data into the TripLog database to verify the changes*@ 
    <p style="color:red;"> Change the sort order to StartDate and remove this comment </>
    <p> </p>
    
    @*When the user clicks ""Add Trip"" on the Home page, the app routes to the
        Trip controller Add action.
        <a is an anchor that creates the URL for routing; No id parameter *@

    <a  style="color:blue;" asp-action="Add" asp-controller="Trip" class="mt-2"><b>Add Trip</b></a>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Destination</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Accommodations</th>
                <th>Things To Do</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Trip trip in Model)
            {
                <tr>
                    <td>@trip.Destination</td>
                    <td>@trip.StartDate?.ToShortDateString()</td>
                    <td>@trip.EndDate?.ToShortDateString()</td>
                    <td>
                        @if (!string.IsNullOrEmpty(trip.Accommodation))
                        {
                            <div>@trip.Accommodation</div>
                            @if (!string.IsNullOrEmpty(trip.AccommodationPhone))
                            {
                                <div>Phone: @trip.AccommodationPhone</div>
                            }
                            @if (!string.IsNullOrEmpty(trip.AccommodationEmail))
                            {
                                <div>Email: @trip.AccommodationEmail</div>
                            }
                        }
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(trip.ThingToDo1))
                        {
                            <div>@trip.ThingToDo1</div>
                        }
                        @if (!string.IsNullOrEmpty(trip.ThingToDo2))
                        {
                            <div>@trip.ThingToDo2</div>
                        }
                        @if (!string.IsNullOrEmpty(trip.ThingToDo3))
                        {
                            <div>@trip.ThingToDo3</div>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

CSC237_TripLog_start1/Views/Shared/_Layout.cshtml
@{ 
    string message = TempData["message"]?.ToString();
    string subheader = ViewBag.SubHeader;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <header class="bg-secondary text-center text-white p-3 mb-2">
            <h1>My Trip Log</h1>
        </header>

        <main role="main">
            @* display temporary message if there is one
                message is set in the TripController when a trip is added to DB *@
            @if (!string.IsNullOrEmpty(message))
            {
                <h2 class="bg-light text-center p-2 mb-1">@message</h2>
            }

            @* display sub header if view has provided text for it; see requirements*@
            @if (!string.IsNullOrEmpty(subheader))
            {
                <h2 class="mt-2 mb-2">@subheader</h2>
            }

            @RenderBody()
        </main>
    </div>

</body>
</html>

CSC237_TripLog_start1/Views/Trip/Add1.cshtml
@model TripViewModel

@{
    ViewBag.Title = "Add Trip - Page 1";
    ViewBag.SubHeader = "Add Trip Destination and Dates";
}

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />

    <div class="form-group">
        <label asp-for="Trip.Destination">Destination</label>
        <input asp-for="Trip.Destination" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Trip.Accommodation">Accommodations</label>
        <input asp-for="Trip.Accommodation" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Trip.StartDate">Start Date</label>
        <input type="text" asp-for="Trip.StartDate" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Trip.EndDate">End Date</label>
        <input type="text" asp-for="Trip.EndDate" class="form-control" />
    </div>
    <div>
        <button type="submit" class="btn btn-dark">Next</button>
        <a asp-action="Cancel" class="btn btn-outline-dark">Cancel</a>
    </div>
</form>

CSC237_TripLog_start1/Views/Trip/Add2.cshtml
@*
    Edit this View*@
@{
}
<p>Edit the Add2 View</p>

CSC237_TripLog_start1/Views/Trip/Add3.cshtml
@*
    Edit this View*@
@{
}
<p>Edit the Add3 View</p>